version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alice
      POSTGRES_PASSWORD: alice
      POSTGRES_DB: alicemultiverse
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alice"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  alice-interface:
    build:
      context: .
      dockerfile: services/alice-interface/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://alice:alice@postgres:5432/alicemultiverse
      - SERVICE_NAME=alice-interface
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/alice-interface:/app
      - ./packages:/packages

  asset-processor:
    build:
      context: .
      dockerfile: services/asset-processor/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=asset-processor
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./services/asset-processor:/app
      - ./packages:/packages
      - ./inbox:/inbox
      - ./organized:/organized

  quality-analyzer:
    build:
      context: .
      dockerfile: services/quality-analyzer/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=quality-analyzer
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./services/quality-analyzer:/app
      - ./packages:/packages

  metadata-extractor:
    build:
      context: .
      dockerfile: services/metadata-extractor/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=metadata-extractor
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./services/metadata-extractor:/app
      - ./packages:/packages

volumes:
  postgres-data:
  redis-data:
