site_name: AliceMultiverse Documentation
site_description: AI Media Organization System - Technical Documentation
site_author: AliceMultiverse Team
repo_url: https://github.com/yourusername/AliceMultiverse
repo_name: AliceMultiverse

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.integrate
  language: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_if_no_docstring: false

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/index.md
    - Basic Usage: user-guide/basic-usage.md
    - Quality Assessment: user-guide/quality-assessment.md
    - Watch Mode: user-guide/watch-mode.md
    - Pipeline System: user-guide/pipeline-system.md
    - API Keys: user-guide/api-keys.md
  - Architecture:
    - Overview: architecture/index.md
    - System Design: architecture/system-design.md
    - Pipeline Architecture: architecture/pipeline-architecture.md
    - Caching Strategy: architecture/caching-strategy.md
    - Design Decisions: architecture/design-decisions.md
  - API Reference:
    - Overview: api/index.md
    - Organizer: api/reference/organizer.md
    - Quality Pipeline: api/reference/quality-pipeline.md
    - Metadata Cache: api/reference/metadata-cache.md
    - API Key Manager: api/reference/api-key-manager.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Organizing Your First Project: tutorials/first-project.md
    - Setting Up Quality Pipeline: tutorials/quality-pipeline-setup.md
    - Custom AI Detection: tutorials/custom-ai-detection.md
  - Developer Guide:
    - Contributing: developer/contributing.md
    - Testing: developer/testing.md
    - Architecture Deep Dive: developer/architecture.md
    - Adding New Features: developer/adding-features.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/AliceMultiverse
  version:
    provider: mike

extra_css:
  - assets/extra.css
