# AliceMultiverse Monorepo Configuration (DEPRECATED)
# This file is kept for historical reference only.
# AliceMultiverse has been simplified to a single application structure.
# The microservices architecture was removed during architecture simplification.

[monorepo]
name = "alicemultiverse"
type = "python"
structure = "single-application"

[development]
# Development settings
python_version = "3.12"
virtual_env = ".venv"
install_mode = "editable"  # pip install -e

[testing]
# Test configuration
test_paths = ["tests"]
coverage_threshold = 80

[deployment]
# Deployment configuration
container_registry = "ghcr.io/alicemultiverse"
kubernetes_namespace = "alice-prod"
docker_build_args = ["--platform", "linux/amd64,linux/arm64"]