# AliceMultiverse Configuration
# This file contains default settings that can be overridden via command-line arguments
# Example: alice --paths.inbox=~/Downloads/ai-images --paths.organized=~/Pictures/AI

paths:
  # Default input directory for media files
  inbox: inbox

  # Default output directory for organized files
  organized: organized

processing:
  # Copy files instead of moving them
  copy_mode: true

  # Force re-analysis of all files (ignores cache)
  force_reindex: false

  # Image understanding enabled by default
  understanding: true

  # Watch mode - continuously monitor for new files
  watch: false

  # Check interval for watch mode (seconds)
  watch_interval: 5

  # Dry run mode - preview without making changes
  dry_run: false

# Quality assessment has been replaced with image understanding
# See pipeline section for configuration

pipeline:
  # Default pipeline mode (basic, standard, premium, custom)
  # basic: DeepSeek only (most cost-effective)
  # standard: DeepSeek + Google 
  # premium: All providers for comprehensive analysis
  mode: basic

  # Custom pipeline stages (when mode is custom)
  stages: []

  # Cost limits for total analysis (USD)
  cost_limits:
    total: 10.0  # Stop processing when this limit is reached
    per_image: 0.01  # Maximum cost per image

  # Detailed analysis (more thorough but costs more)
  detailed: false

  # Understanding settings
  understanding:
    # Which tags to extract
    extract_tags: true
    generate_prompt: true
    
    # Custom instructions for all analyses
    custom_instructions: null
    
    # Provider selection (null = cheapest available)
    preferred_provider: null

# Output structure settings
output:
  # Date format for organized folders
  date_format: "%Y-%m-%d"

  # Number of digits for sequential numbering
  sequence_digits: 5

  # File naming pattern: {project}-{number}.{ext}
  naming_pattern: "{project}-{number:0{digits}d}{ext}"

# Metadata settings
metadata:
  # Cache version (increment to force cache rebuild)
  cache_version: "3.0.0"

  # Metadata folder name
  folder_name: ".metadata"

# File type settings
file_types:
  # Image extensions to process
  # AI-generated content focus: only essential formats
  image_extensions:
    - .jpg
    - .jpeg
    - .png

  # Video extensions to process
  video_extensions:
    - .mp4
    - .mov

# AI generator detection patterns
ai_generators:
  image:
    - stablediffusion
    - midjourney
    - dalle
    - comfyui
    - flux
    - leonardo
    - firefly

  video:
    - runway
    - kling
    - pika
    - stable-video
    - animatediff
    - deforum
    - modelscope
    - zeroscope
    - haiper
    - genmo

# Provider settings
providers:
  anthropic:
    # Available Claude models
    models:
      claude-3-opus-20240229:
        max_tokens: 4096
        vision: true
        context_window: 200000
      claude-3-sonnet-20240229:
        max_tokens: 4096
        vision: true
        context_window: 200000
      claude-3-haiku-20240307:
        max_tokens: 4096
        vision: true
        context_window: 200000
      claude-3-5-sonnet-20241022:
        max_tokens: 8192
        vision: true
        context_window: 200000
    
    # Default model for image understanding
    default_model: claude-3-5-sonnet-20241022
    
    # API settings
    max_retries: 3
    timeout: 30
    
  # Connection pool settings
  database:
    # Base pool size - number of persistent connections
    pool_size: 20  # Increased from 10 for better concurrency
    
    # Maximum overflow - temporary connections when pool exhausted
    max_overflow: 40  # Increased from 20 to handle spikes
    
    # Timeout waiting for connection from pool (seconds)
    pool_timeout: 30
    
    # Recycle connections after this many seconds
    pool_recycle: 1800  # Reduced from 3600 to prevent stale connections
    
    # Check connection health before use
    pool_pre_ping: true
    
    # Log pool events for debugging (set to false in production)
    pool_echo: false
    
  # Event system settings
  events:
    # PostgreSQL NOTIFY/LISTEN settings
    channel_prefix: alice_events
    cleanup_interval: 3600  # Clean up old events every hour
    retention_days: 7       # Keep events for 7 days

# Storage configuration
storage:
  # Define multiple storage locations
  locations:
    # Primary organized storage
    primary:
      type: local
      path: organized  # Relative to current directory
      purpose: organized  # Where organized files go
      
    # Inbox for new files
    inbox:
      type: local
      path: inbox
      scan: true  # Monitor for new files
      purpose: inbox
      
    # Example: External drive
    # external:
    #   type: local
    #   path: /Volumes/External/AI
    #   scan: true
    #   purpose: archive
    
    # Example: Cloud storage
    # cloud:
    #   type: s3
    #   bucket: my-ai-media
    #   prefix: images/
    #   region: us-east-1
    #   purpose: backup
    
  # Rules for automatic filing
  rules:
    # - match: "*.mp4"
    #   location: cloud  # Videos go to cloud
    # - match: "project:client-*"
    #   location: external  # Client work to external
    - default: primary
    
  # Search index configuration
  search:
    # Search backend (sqlite, meilisearch, elasticsearch)
    backend: sqlite
    
    # SQLite settings
    sqlite:
      path: .alicemultiverse/search.db
      
    # Future: Meilisearch settings
    # meilisearch:
    #   url: http://localhost:7700
    #   api_key: null
    
  # Location registry
  registry:
    # Track file locations by hash
    enable_tracking: true
    
    # Scan interval for changes (seconds)
    scan_interval: 300

# Logging settings
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR)
  level: INFO

  # Show progress bars
  show_progress: true
