# AliceMultiverse Configuration
# This file contains default settings that can be overridden via command-line arguments
# Example: alice --paths.inbox=~/Downloads/ai-images --paths.organized=~/Pictures/AI

paths:
  # Default input directory for media files
  inbox: inbox

  # Default output directory for organized files
  organized: organized

# Storage configuration
storage:
  # Where to store DuckDB search index
  search_db: "data/search.duckdb"
  
  # Paths where projects can be stored
  # Can include local paths or cloud URLs (s3://, gcs://)
  project_paths:
    - "projects"       # Local projects directory
    # - "s3://my-bucket/projects"  # Example S3 path
    # - "gcs://my-bucket/projects" # Example GCS path
  
  # Where to find existing assets for reuse
  asset_paths:
    - "organized"      # Default organized output
    - "inbox"          # Also check inbox
    # - "/Volumes/External/AI-Assets"  # Example external drive
  
  # Where rejected/soft-deleted assets go
  sorted_out_path: "sorted-out"

processing:
  # Copy files instead of moving them
  copy_mode: true

  # Force re-analysis of all files (ignores cache)
  force_reindex: false

  # Image understanding enabled by default
  understanding: true

  # Watch mode - continuously monitor for new files
  watch: false

  # Check interval for watch mode (seconds)
  watch_interval: 5

  # Dry run mode - preview without making changes
  dry_run: false

# Quality assessment has been replaced with image understanding
# See pipeline section for configuration

pipeline:
  # Default pipeline mode (basic, standard, premium, custom)
  # basic: DeepSeek only (most cost-effective)
  # standard: DeepSeek + Google 
  # premium: All providers for comprehensive analysis
  mode: basic

  # Custom pipeline stages (when mode is custom)
  stages: []

  # Cost limits for total analysis (USD)
  cost_limits:
    total: 10.0  # Stop processing when this limit is reached
    per_image: 0.01  # Maximum cost per image

  # Detailed analysis (more thorough but costs more)
  detailed: false

  # Understanding settings
  understanding:
    # Which tags to extract
    extract_tags: true
    generate_prompt: true
    
    # Custom instructions for all analyses
    custom_instructions: null
    
    # Provider selection (null = cheapest available)
    preferred_provider: null

# Output structure settings
output:
  # Date format for organized folders
  date_format: "%Y-%m-%d"

  # Number of digits for sequential numbering
  sequence_digits: 5

  # File naming pattern: {project}-{number}.{ext}
  naming_pattern: "{project}-{number:0{digits}d}{ext}"

# Metadata settings
metadata:
  # Cache version (increment to force cache rebuild)
  cache_version: "3.0.0"

  # Metadata folder name
  folder_name: ".metadata"

# File type settings
file_types:
  # Image extensions to process
  # AI-generated content focus: only essential formats
  image_extensions:
    - .jpg
    - .jpeg
    - .png

  # Video extensions to process
  video_extensions:
    - .mp4
    - .mov

# AI generator detection patterns
ai_generators:
  image:
    - stablediffusion
    - midjourney
    - dalle
    - comfyui
    - flux
    - leonardo
    - firefly

  video:
    - runway
    - kling
    - pika
    - stable-video
    - animatediff
    - deforum
    - modelscope
    - zeroscope
    - haiper
    - genmo

# Provider settings
providers:
  anthropic:
    # Available Claude models
    models:
      # Claude 4 models (latest)
      claude-opus-4-20250115:
        max_tokens: 8192
        vision: true
        context_window: 300000
      claude-sonnet-4-20250115:
        max_tokens: 8192
        vision: true
        context_window: 200000
      # Claude 3.5 models (still good)
      claude-3-5-sonnet-20241022:
        max_tokens: 8192
        vision: true
        context_window: 200000
      # Claude 3 models (legacy but cheaper)
      claude-3-opus-20240229:
        max_tokens: 4096
        vision: true
        context_window: 200000
      claude-3-sonnet-20240229:
        max_tokens: 4096
        vision: true
        context_window: 200000
      claude-3-haiku-20240307:
        max_tokens: 4096
        vision: true
        context_window: 200000
    
    # Default model for image understanding
    default_model: claude-opus-4-20250115
    
    # API settings
    max_retries: 3
    timeout: 30
    
  # Connection pool settings
  database:
    # Base pool size - number of persistent connections
    pool_size: 20  # Increased from 10 for better concurrency
    
    # Maximum overflow - temporary connections when pool exhausted
    max_overflow: 40  # Increased from 20 to handle spikes
    
    # Timeout waiting for connection from pool (seconds)
    pool_timeout: 30
    
    # Recycle connections after this many seconds
    pool_recycle: 1800  # Reduced from 3600 to prevent stale connections
    
    # Check connection health before use
    pool_pre_ping: true
    
    # Log pool events for debugging (set to false in production)
    pool_echo: false
    
  # Event system settings
  events:
    # PostgreSQL NOTIFY/LISTEN settings
    channel_prefix: alice_events
    cleanup_interval: 3600  # Clean up old events every hour
    retention_days: 7       # Keep events for 7 days

# Additional storage configuration (future expansion)
# This section is reserved for advanced storage features like
# multi-location storage, cloud integration, and registry tracking

# Logging settings
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR)
  level: INFO

  # Show progress bars
  show_progress: true
