"""Initial asset system schema

Revision ID: cbb2da6f61b1
Revises:
Create Date: 2025-05-26 14:01:36.798927

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbb2da6f61b1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("creative_context", sa.JSON(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_projects_created", "projects", ["created_at"], unique=False)
    op.create_index("idx_projects_name", "projects", ["name"], unique=False)
    op.create_table(
        "assets",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("file_path_verified", sa.DateTime(), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("media_type", sa.String(length=20), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.String(length=50), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "last_seen", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column("generation_params", sa.JSON(), nullable=True),
        sa.Column("embedded_metadata", sa.JSON(), nullable=True),
        sa.Column("analysis_results", sa.JSON(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_index("idx_assets_created", "assets", ["first_seen"], unique=False)
    op.create_index("idx_assets_project", "assets", ["project_id"], unique=False)
    op.create_index("idx_assets_role", "assets", ["role"], unique=False)
    op.create_index("idx_assets_source", "assets", ["source_type"], unique=False)
    op.create_index("idx_assets_type", "assets", ["media_type"], unique=False)
    op.create_index(op.f("ix_assets_file_path"), "assets", ["file_path"], unique=False)
    op.create_table(
        "asset_paths",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "discovered_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("last_verified", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_hash"],
            ["assets.content_hash"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash", "file_path", name="uq_asset_path"),
    )
    op.create_index("idx_asset_paths_active", "asset_paths", ["is_active"], unique=False)
    op.create_index("idx_asset_paths_lookup", "asset_paths", ["file_path"], unique=False)
    op.create_table(
        "asset_relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("child_id", sa.String(length=64), nullable=True),
        sa.Column("relationship_type", sa.String(length=20), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["assets.content_hash"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["assets.content_hash"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_id", "child_id", "relationship_type", name="uq_asset_relationship"
        ),
    )
    op.create_index("idx_relationships_child", "asset_relationships", ["child_id"], unique=False)
    op.create_index("idx_relationships_parent", "asset_relationships", ["parent_id"], unique=False)
    op.create_index(
        "idx_relationships_type", "asset_relationships", ["relationship_type"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=True),
        sa.Column("tag_type", sa.String(length=20), nullable=True),
        sa.Column("tag_value", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.content_hash"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "tag_type", "tag_value", name="uq_asset_tag"),
    )
    op.create_index("idx_tags_asset", "tags", ["asset_id"], unique=False)
    op.create_index("idx_tags_type_value", "tags", ["tag_type", "tag_value"], unique=False)
    op.create_index("idx_tags_value", "tags", ["tag_value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tags_value", table_name="tags")
    op.drop_index("idx_tags_type_value", table_name="tags")
    op.drop_index("idx_tags_asset", table_name="tags")
    op.drop_table("tags")
    op.drop_index("idx_relationships_type", table_name="asset_relationships")
    op.drop_index("idx_relationships_parent", table_name="asset_relationships")
    op.drop_index("idx_relationships_child", table_name="asset_relationships")
    op.drop_table("asset_relationships")
    op.drop_index("idx_asset_paths_lookup", table_name="asset_paths")
    op.drop_index("idx_asset_paths_active", table_name="asset_paths")
    op.drop_table("asset_paths")
    op.drop_index(op.f("ix_assets_file_path"), table_name="assets")
    op.drop_index("idx_assets_type", table_name="assets")
    op.drop_index("idx_assets_source", table_name="assets")
    op.drop_index("idx_assets_role", table_name="assets")
    op.drop_index("idx_assets_project", table_name="assets")
    op.drop_index("idx_assets_created", table_name="assets")
    op.drop_table("assets")
    op.drop_index("idx_projects_name", table_name="projects")
    op.drop_index("idx_projects_created", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
