[project]
name = "alice-events"
version = "0.1.0"
description = "Event definitions and infrastructure for AliceMultiverse"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "redis>=5.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["alice_events"]