[project]
name = "alice-config"
version = "0.1.0"
description = "Configuration management for AliceMultiverse"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "omegaconf>=2.3.0",
    "pydantic>=2.0.0",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["alice_config"]