---
{{- if .Values.database.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "alice-service.databaseSecretName" .}}
  labels:
    {{- include "alice-service.labels" . | nindent 4}}
type: Opaque
stringData:
  username: {{.Values.database.user}}
  {{- if .Values.database.password}}
  password: {{.Values.database.password}}
  {{- else}}
  password: {{randAlphaNum 32 | quote}}
  {{- end}}
  {{- $dbName := include "alice-service.databaseName" .}}
  {{- $clusterName := include "alice-service.databaseClusterName" .}}
  uri: >-
    postgresql://{{.Values.database.user}}:{{.Values.database.password | default (randAlphaNum 32)}}@{{$clusterName}}-rw:5432/{{$dbName}}
{{- end}}
---
{{- if .Values.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "alice-service.fullname" .}}-secrets
  labels:
    {{- include "alice-service.labels" . | nindent 4}}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2}}
{{- end}}
