---
  {{- if .Values.serviceAccount.create -}}
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: {{include "alice-service.serviceAccountName" .}}
    labels:
      {{- include "alice-service.labels" . | nindent 6}}
    {{- with .Values.serviceAccount.annotations}}
    annotations:
      {{- toYaml . | nindent 6}}
    {{- end}}
  {{- end}}
